application: code-tutor
version: 1
runtime: python
default_expiration: "1m"
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /ace
  static_dir: ace
- url: /google-code-prettify
  static_dir: google-code-prettify
- url: /.*
  script: main.py
